site_name: Portal DG DHL
site_url: https://portaldangerousgoods.github.io/dpdhl/
theme:
  name: material
  logo: logo-dhl.png
  favicon: logo-dhl.png
  features:
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - extra.js

nav:
  - Início: index.md
  - FAQ Técnico: faq.md
  - Produtos:
      - Baterias de Lítio: baterias.md
      - Bebidas Alcoólicas: bebidas.md
      - Gelo Seco: gelo-seco.md
      - Perfumes: perfumes.md
      - Produtos Biológicos: biologicos.md
      - Cargas Totais (Full DG): full-dg.md
  - Aprovação de Conta: aprovacao.md
  - Documentos Exigidos: documentos.md 
