site_name: Portal DG DHL
site_url: https://portaldangerousgoods.github.io/dpdhl/
repo_url: https://github.com/portaldangerousgoods/dpdhl
repo_name: GitHub

theme:
  name: material
  language: pt-BR
  logo: logo-dhl.png
  font:
    text: "Barlow"
    code: "Fira Code"
  palette:
    - scheme: default
      primary: yellow
      accent: red
  custom_dir: docs/overrides

nav:
  - Início: index.md
  - FAQ Técnico: faq.md
  - Como aprovar uma conta: aprovacao.md
  - Documentos exigidos: documentos.md
  - Produtos Biológicos: biologicos.md
  - Transporte de Gelo Seco: gelo-seco.md

extra_javascript:
  - extra.js

extra_css:
  - stylesheets/menu-lateral.css
  - stylesheets/extra.css
